DROP TABLE IF EXISTS genre, mpa, users, films, films_genre, friendship, likes;

CREATE TABLE IF NOT EXISTS users (
id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
email varchar(40) NOT NULL UNIQUE,
login varchar(20) NOT NULL UNIQUE,
name varchar(40) NOT NULL,
birthday date NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(40),
description text,
release_date date,
duration integer,
mpa_id integer
);

CREATE TABLE IF NOT EXISTS genre (
id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(40)
);

CREATE TABLE IF NOT EXISTS films_genre (
film_id integer,
genre_id integer
);

CREATE TABLE IF NOT EXISTS mpa (
id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(10)
);

CREATE TABLE IF NOT EXISTS friendship (
user_id integer,
friend_id integer,
confirmed boolean
);

CREATE TABLE IF NOT EXISTS likes (
user_id integer,
film_id integer
);